name: ML Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-dev python3-pip python3-setuptools

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --no-cache-dir -r requirements.txt
        pip install pytest pytest-cov
        python -c "import matplotlib; print('matplotlib version:', matplotlib.__version__)"
        python -c "import torch; print('torch version:', torch.__version__)"

    - name: Configure matplotlib backend
      run: |
        mkdir -p ~/.config/matplotlib
        echo "backend: Agg" > ~/.config/matplotlib/matplotlibrc

    - name: List directory structure
      run: ls -R
      
    - name: Run tests
      run: |
        python -m pytest tests/test_model.py -v --cov=./ --cov-report=xml
      
    - name: Train and deploy model
      run: |
        python deploy.py

    - name: Upload trained model
      uses: actions/upload-artifact@v4
      with:
        name: trained-model
        path: models/
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}